/*Foreign Keys*/
ALTER TABLE PROVINCE
	ADD CONSTRAINT PROVINCE_COUNTRY_FK FOREIGN KEY
	(ID_COUNTRY) REFERENCES COUNTRY(ID_COUNTRY);

ALTER TABLE CANTON
	ADD CONSTRAINT CANTON_PROVINCE_FK FOREIGN KEY
	(ID_PROVINCE) REFERENCES PROVINCE(ID_PROVINCE);

ALTER TABLE DISTRICT
	ADD CONSTRAINT DISTRICT_CANTON_FK FOREIGN KEY
	(ID_CANTON) REFERENCES CANTON(ID_CANTON);

ALTER TABLE COMMUNITY
	ADD CONSTRAINT COMMUNITY_DISTRICT_FK FOREIGN KEY
	(ID_DISTRICT) REFERENCES DISTRICT(ID_DISTRICT);

ALTER TABLE log_In
	ADD CONSTRAINT log_In_USER_TYPE_FK FOREIGN KEY
	(ID_USER_TYPE) REFERENCES USER_TYPE(ID_USER_TYPE);

ALTER TABLE PERSON
	ADD CONSTRAINT PERSON_COMMUNITY_FK FOREIGN KEY
	(ID_COMMUNITY) REFERENCES COMMUNITY(ID_COMMUNITY);

ALTER TABLE PERSON
	ADD CONSTRAINT PERSON_log_In_FK FOREIGN KEY
	(ID_log_In) REFERENCES log_In(ID_log_In);

ALTER TABLE PERSON_PHOTO
	ADD CONSTRAINT PERSON_PHOTO_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER TABLE PHONE
	ADD CONSTRAINT PHONE_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);
--
ALTER TABLE PERSONXCOUNTRY
	ADD CONSTRAINT PERSONXCOUNTRY_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER TABLE PERSONXCOUNTRY
	ADD CONSTRAINT PERSONXCOUNTRY_COUNTRY_FK FOREIGN KEY
	(ID_COUNTRY) REFERENCES COUNTRY(ID_COUNTRY);

ALTER TABLE EMAIL
	ADD CONSTRAINT EMAIL_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);
--
ALTER TABLE PERSONXCATEGORY
	ADD CONSTRAINT PERSONXCATEGORY_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER TABLE PERSONXCATEGORY
	ADD CONSTRAINT PERSONXCATEGORY_CATEGORY_FK FOREIGN KEY
	(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY);

ALTER TABLE PROPOSAL
	ADD CONSTRAINT PROPOSAL_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);
--
ALTER TABLE PROPOSAL_PHOTO
	ADD CONSTRAINT PROPOSAL_PHOTO_PROPOSAL_FK FOREIGN KEY
	(ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER TABLE COMMENTARY
	ADD CONSTRAINT COMMENTARY_PROPOSAL_FK FOREIGN KEY
	(ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER TABLE COMMENTARY
	ADD CONSTRAINT COMMENTARY_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);

ALTER TABLE PROPOSALXCATEGORY
	ADD CONSTRAINT PROPOSALXCATEGORY_PROPOSAL_FK FOREIGN KEY
	(ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER TABLE PROPOSALXCATEGORY
	ADD CONSTRAINT PROPOSALXCATEGORY_CATEGORY_FK FOREIGN KEY
	(ID_CATEGORY) REFERENCES CATEGORY(ID_CATEGORY);

ALTER TABLE VOTE
	ADD CONSTRAINT VOTE_PROPOSAL_FK FOREIGN KEY
	(ID_PROPOSAL) REFERENCES PROPOSAL(ID_PROPOSAL);

ALTER TABLE VOTE
	ADD CONSTRAINT VOTE_PERSON_FK FOREIGN KEY
	(ID_PERSON) REFERENCES PERSON(ID_PERSON);
