/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author jalej
 */
public class Catalogue extends javax.swing.JFrame {

    /**
     * Creates new form Catalogue
     */
    public Catalogue() {
        initComponents();
        this.setLocationRelativeTo(null);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabPaneCountry = new javax.swing.JTabbedPane();
        tabCountryPanel = new javax.swing.JPanel();
        countryScrollPane = new javax.swing.JScrollPane();
        listCountry = new javax.swing.JList<String>();
        submitCountryButton = new javax.swing.JButton();
        addCountryButton = new javax.swing.JButton();
        editCountryButton = new javax.swing.JButton();
        deleteCountryButton = new javax.swing.JButton();
        exitButtonCountry = new javax.swing.JButton();
        tabProvincePanel = new javax.swing.JPanel();
        provinceScrollPane = new javax.swing.JScrollPane();
        listCountry1 = new javax.swing.JList<String>();
        submitProvinceButton = new javax.swing.JButton();
        addProvinceButton = new javax.swing.JButton();
        editProvinceButton = new javax.swing.JButton();
        deleteProvinceButton = new javax.swing.JButton();
        exitButtonProvince = new javax.swing.JButton();
        tabCategoryPanel = new javax.swing.JPanel();
        categoryScrollPane = new javax.swing.JScrollPane();
        listCountry2 = new javax.swing.JList<String>();
        submitCategoryButton = new javax.swing.JButton();
        addCategoryButton = new javax.swing.JButton();
        editCategoryButton = new javax.swing.JButton();
        deleteCategoryButton = new javax.swing.JButton();
        exitButtonCategory = new javax.swing.JButton();
        tabDistrictPanel = new javax.swing.JPanel();
        districtScrollPane = new javax.swing.JScrollPane();
        listCountry3 = new javax.swing.JList<String>();
        submitDistrictButton = new javax.swing.JButton();
        addDistrictButton = new javax.swing.JButton();
        editDistrictButton = new javax.swing.JButton();
        deleteDistrictButton = new javax.swing.JButton();
        exitButtonDistrict = new javax.swing.JButton();
        tabCantonPanel = new javax.swing.JPanel();
        cantonScrollPane = new javax.swing.JScrollPane();
        listCountry4 = new javax.swing.JList<String>();
        submitCantonButton = new javax.swing.JButton();
        addCantonButton = new javax.swing.JButton();
        editCantonButton = new javax.swing.JButton();
        deleteCantonButton = new javax.swing.JButton();
        exitButtonCanton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        TabPaneCountry.setBackground(new java.awt.Color(45, 49, 66));
        TabPaneCountry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 192, 192), 2));
        TabPaneCountry.setForeground(new java.awt.Color(255, 255, 255));

        tabCountryPanel.setBackground(new java.awt.Color(45, 49, 66));
        tabCountryPanel.setForeground(new java.awt.Color(255, 255, 255));

        listCountry.setBackground(new java.awt.Color(79, 93, 117));
        listCountry.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        listCountry.setForeground(new java.awt.Color(255, 255, 255));
        countryScrollPane.setViewportView(listCountry);

        submitCountryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enter_2_40px.png"))); // NOI18N
        submitCountryButton.setBorder(null);
        submitCountryButton.setBorderPainted(false);
        submitCountryButton.setContentAreaFilled(false);
        submitCountryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addCountryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_png.png"))); // NOI18N
        addCountryButton.setBorder(null);
        addCountryButton.setBorderPainted(false);
        addCountryButton.setContentAreaFilled(false);
        addCountryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editCountryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editCountryButton.setBorder(null);
        editCountryButton.setBorderPainted(false);
        editCountryButton.setContentAreaFilled(false);
        editCountryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteCountryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash.png"))); // NOI18N
        deleteCountryButton.setBorder(null);
        deleteCountryButton.setBorderPainted(false);
        deleteCountryButton.setContentAreaFilled(false);
        deleteCountryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitButtonCountry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelNaranja40.png"))); // NOI18N
        exitButtonCountry.setBorder(null);
        exitButtonCountry.setBorderPainted(false);
        exitButtonCountry.setContentAreaFilled(false);
        exitButtonCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButtonCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCountryPanelLayout = new javax.swing.GroupLayout(tabCountryPanel);
        tabCountryPanel.setLayout(tabCountryPanelLayout);
        tabCountryPanelLayout.setHorizontalGroup(
            tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCountryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCountryPanelLayout.createSequentialGroup()
                        .addComponent(countryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addGroup(tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editCountryButton)
                            .addComponent(addCountryButton)
                            .addComponent(deleteCountryButton)))
                    .addGroup(tabCountryPanelLayout.createSequentialGroup()
                        .addComponent(exitButtonCountry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitCountryButton)))
                .addGap(42, 42, 42))
        );
        tabCountryPanelLayout.setVerticalGroup(
            tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCountryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabCountryPanelLayout.createSequentialGroup()
                        .addComponent(addCountryButton)
                        .addGap(18, 18, 18)
                        .addComponent(editCountryButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCountryButton)
                        .addGap(30, 30, 30))
                    .addComponent(countryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(tabCountryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitCountryButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButtonCountry, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        TabPaneCountry.addTab("Country", tabCountryPanel);

        tabProvincePanel.setBackground(new java.awt.Color(45, 49, 66));
        tabProvincePanel.setForeground(new java.awt.Color(255, 255, 255));

        listCountry1.setBackground(new java.awt.Color(79, 93, 117));
        listCountry1.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        listCountry1.setForeground(new java.awt.Color(255, 255, 255));
        provinceScrollPane.setViewportView(listCountry1);

        submitProvinceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enter_2_40px.png"))); // NOI18N
        submitProvinceButton.setBorder(null);
        submitProvinceButton.setBorderPainted(false);
        submitProvinceButton.setContentAreaFilled(false);
        submitProvinceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addProvinceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_png.png"))); // NOI18N
        addProvinceButton.setBorder(null);
        addProvinceButton.setBorderPainted(false);
        addProvinceButton.setContentAreaFilled(false);
        addProvinceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editProvinceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editProvinceButton.setBorder(null);
        editProvinceButton.setBorderPainted(false);
        editProvinceButton.setContentAreaFilled(false);
        editProvinceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteProvinceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash.png"))); // NOI18N
        deleteProvinceButton.setBorder(null);
        deleteProvinceButton.setBorderPainted(false);
        deleteProvinceButton.setContentAreaFilled(false);
        deleteProvinceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitButtonProvince.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelNaranja40.png"))); // NOI18N
        exitButtonProvince.setBorder(null);
        exitButtonProvince.setBorderPainted(false);
        exitButtonProvince.setContentAreaFilled(false);
        exitButtonProvince.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tabProvincePanelLayout = new javax.swing.GroupLayout(tabProvincePanel);
        tabProvincePanel.setLayout(tabProvincePanelLayout);
        tabProvincePanelLayout.setHorizontalGroup(
            tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProvincePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabProvincePanelLayout.createSequentialGroup()
                        .addComponent(provinceScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addGroup(tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editProvinceButton)
                            .addComponent(addProvinceButton)
                            .addComponent(deleteProvinceButton)))
                    .addGroup(tabProvincePanelLayout.createSequentialGroup()
                        .addComponent(exitButtonProvince)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitProvinceButton)))
                .addGap(42, 42, 42))
        );
        tabProvincePanelLayout.setVerticalGroup(
            tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProvincePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabProvincePanelLayout.createSequentialGroup()
                        .addComponent(addProvinceButton)
                        .addGap(18, 18, 18)
                        .addComponent(editProvinceButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteProvinceButton)
                        .addGap(30, 30, 30))
                    .addComponent(provinceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(tabProvincePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitProvinceButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButtonProvince, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        TabPaneCountry.addTab("Province", tabProvincePanel);

        tabCategoryPanel.setBackground(new java.awt.Color(45, 49, 66));
        tabCategoryPanel.setForeground(new java.awt.Color(255, 255, 255));

        listCountry2.setBackground(new java.awt.Color(79, 93, 117));
        listCountry2.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        listCountry2.setForeground(new java.awt.Color(255, 255, 255));
        categoryScrollPane.setViewportView(listCountry2);

        submitCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enter_2_40px.png"))); // NOI18N
        submitCategoryButton.setBorder(null);
        submitCategoryButton.setBorderPainted(false);
        submitCategoryButton.setContentAreaFilled(false);
        submitCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_png.png"))); // NOI18N
        addCategoryButton.setBorder(null);
        addCategoryButton.setBorderPainted(false);
        addCategoryButton.setContentAreaFilled(false);
        addCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editCategoryButton.setBorder(null);
        editCategoryButton.setBorderPainted(false);
        editCategoryButton.setContentAreaFilled(false);
        editCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteCategoryButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash.png"))); // NOI18N
        deleteCategoryButton.setBorder(null);
        deleteCategoryButton.setBorderPainted(false);
        deleteCategoryButton.setContentAreaFilled(false);
        deleteCategoryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitButtonCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelNaranja40.png"))); // NOI18N
        exitButtonCategory.setBorder(null);
        exitButtonCategory.setBorderPainted(false);
        exitButtonCategory.setContentAreaFilled(false);
        exitButtonCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tabCategoryPanelLayout = new javax.swing.GroupLayout(tabCategoryPanel);
        tabCategoryPanel.setLayout(tabCategoryPanelLayout);
        tabCategoryPanelLayout.setHorizontalGroup(
            tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCategoryPanelLayout.createSequentialGroup()
                        .addComponent(categoryScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addGroup(tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editCategoryButton)
                            .addComponent(addCategoryButton)
                            .addComponent(deleteCategoryButton)))
                    .addGroup(tabCategoryPanelLayout.createSequentialGroup()
                        .addComponent(exitButtonCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitCategoryButton)))
                .addGap(42, 42, 42))
        );
        tabCategoryPanelLayout.setVerticalGroup(
            tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabCategoryPanelLayout.createSequentialGroup()
                        .addComponent(addCategoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(editCategoryButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCategoryButton)
                        .addGap(30, 30, 30))
                    .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(tabCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitCategoryButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButtonCategory, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        TabPaneCountry.addTab("Category", tabCategoryPanel);

        tabDistrictPanel.setBackground(new java.awt.Color(45, 49, 66));
        tabDistrictPanel.setForeground(new java.awt.Color(255, 255, 255));

        listCountry3.setBackground(new java.awt.Color(79, 93, 117));
        listCountry3.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        listCountry3.setForeground(new java.awt.Color(255, 255, 255));
        districtScrollPane.setViewportView(listCountry3);

        submitDistrictButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enter_2_40px.png"))); // NOI18N
        submitDistrictButton.setBorder(null);
        submitDistrictButton.setBorderPainted(false);
        submitDistrictButton.setContentAreaFilled(false);
        submitDistrictButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addDistrictButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_png.png"))); // NOI18N
        addDistrictButton.setBorder(null);
        addDistrictButton.setBorderPainted(false);
        addDistrictButton.setContentAreaFilled(false);
        addDistrictButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editDistrictButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editDistrictButton.setBorder(null);
        editDistrictButton.setBorderPainted(false);
        editDistrictButton.setContentAreaFilled(false);
        editDistrictButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteDistrictButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash.png"))); // NOI18N
        deleteDistrictButton.setBorder(null);
        deleteDistrictButton.setBorderPainted(false);
        deleteDistrictButton.setContentAreaFilled(false);
        deleteDistrictButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitButtonDistrict.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelNaranja40.png"))); // NOI18N
        exitButtonDistrict.setBorder(null);
        exitButtonDistrict.setBorderPainted(false);
        exitButtonDistrict.setContentAreaFilled(false);
        exitButtonDistrict.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout tabDistrictPanelLayout = new javax.swing.GroupLayout(tabDistrictPanel);
        tabDistrictPanel.setLayout(tabDistrictPanelLayout);
        tabDistrictPanelLayout.setHorizontalGroup(
            tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDistrictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabDistrictPanelLayout.createSequentialGroup()
                        .addComponent(districtScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addGroup(tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editDistrictButton)
                            .addComponent(addDistrictButton)
                            .addComponent(deleteDistrictButton)))
                    .addGroup(tabDistrictPanelLayout.createSequentialGroup()
                        .addComponent(exitButtonDistrict)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitDistrictButton)))
                .addGap(42, 42, 42))
        );
        tabDistrictPanelLayout.setVerticalGroup(
            tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDistrictPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabDistrictPanelLayout.createSequentialGroup()
                        .addComponent(addDistrictButton)
                        .addGap(18, 18, 18)
                        .addComponent(editDistrictButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteDistrictButton)
                        .addGap(30, 30, 30))
                    .addComponent(districtScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(tabDistrictPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitDistrictButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButtonDistrict, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        TabPaneCountry.addTab("District", tabDistrictPanel);

        tabCantonPanel.setBackground(new java.awt.Color(45, 49, 66));
        tabCantonPanel.setForeground(new java.awt.Color(255, 255, 255));

        listCountry4.setBackground(new java.awt.Color(79, 93, 117));
        listCountry4.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        listCountry4.setForeground(new java.awt.Color(255, 255, 255));
        cantonScrollPane.setViewportView(listCountry4);

        submitCantonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/enter_2_40px.png"))); // NOI18N
        submitCantonButton.setBorder(null);
        submitCantonButton.setBorderPainted(false);
        submitCantonButton.setContentAreaFilled(false);
        submitCantonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        addCantonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_png.png"))); // NOI18N
        addCantonButton.setBorder(null);
        addCantonButton.setBorderPainted(false);
        addCantonButton.setContentAreaFilled(false);
        addCantonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        editCantonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        editCantonButton.setBorder(null);
        editCantonButton.setBorderPainted(false);
        editCantonButton.setContentAreaFilled(false);
        editCantonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteCantonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/trash.png"))); // NOI18N
        deleteCantonButton.setBorder(null);
        deleteCantonButton.setBorderPainted(false);
        deleteCantonButton.setContentAreaFilled(false);
        deleteCantonButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        exitButtonCanton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancelNaranja40.png"))); // NOI18N
        exitButtonCanton.setBorder(null);
        exitButtonCanton.setBorderPainted(false);
        exitButtonCanton.setContentAreaFilled(false);
        exitButtonCanton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButtonCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonCantonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabCantonPanelLayout = new javax.swing.GroupLayout(tabCantonPanel);
        tabCantonPanel.setLayout(tabCantonPanelLayout);
        tabCantonPanelLayout.setHorizontalGroup(
            tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCantonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCantonPanelLayout.createSequentialGroup()
                        .addComponent(cantonScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                        .addGap(50, 50, 50)
                        .addGroup(tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editCantonButton)
                            .addComponent(addCantonButton)
                            .addComponent(deleteCantonButton)))
                    .addGroup(tabCantonPanelLayout.createSequentialGroup()
                        .addComponent(exitButtonCanton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitCantonButton)))
                .addGap(42, 42, 42))
        );
        tabCantonPanelLayout.setVerticalGroup(
            tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCantonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(tabCantonPanelLayout.createSequentialGroup()
                        .addComponent(addCantonButton)
                        .addGap(18, 18, 18)
                        .addComponent(editCantonButton)
                        .addGap(18, 18, 18)
                        .addComponent(deleteCantonButton)
                        .addGap(30, 30, 30))
                    .addComponent(cantonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(tabCantonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitCantonButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(exitButtonCanton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(25, 25, 25))
        );

        TabPaneCountry.addTab("Canton", tabCantonPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPaneCountry)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabPaneCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonCantonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonCantonActionPerformed

    private void exitButtonCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonCountryActionPerformed
        maqueta newWindow = new maqueta();
        
        newWindow.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_exitButtonCountryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabPaneCountry;
    private javax.swing.JButton addCantonButton;
    private javax.swing.JButton addCategoryButton;
    private javax.swing.JButton addCountryButton;
    private javax.swing.JButton addDistrictButton;
    private javax.swing.JButton addProvinceButton;
    private javax.swing.JScrollPane cantonScrollPane;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JScrollPane countryScrollPane;
    private javax.swing.JButton deleteCantonButton;
    private javax.swing.JButton deleteCategoryButton;
    private javax.swing.JButton deleteCountryButton;
    private javax.swing.JButton deleteDistrictButton;
    private javax.swing.JButton deleteProvinceButton;
    private javax.swing.JScrollPane districtScrollPane;
    private javax.swing.JButton editCantonButton;
    private javax.swing.JButton editCategoryButton;
    private javax.swing.JButton editCountryButton;
    private javax.swing.JButton editDistrictButton;
    private javax.swing.JButton editProvinceButton;
    private javax.swing.JButton exitButtonCanton;
    private javax.swing.JButton exitButtonCategory;
    private javax.swing.JButton exitButtonCountry;
    private javax.swing.JButton exitButtonDistrict;
    private javax.swing.JButton exitButtonProvince;
    private javax.swing.JList<String> listCountry;
    private javax.swing.JList<String> listCountry1;
    private javax.swing.JList<String> listCountry2;
    private javax.swing.JList<String> listCountry3;
    private javax.swing.JList<String> listCountry4;
    private javax.swing.JScrollPane provinceScrollPane;
    private javax.swing.JButton submitCantonButton;
    private javax.swing.JButton submitCategoryButton;
    private javax.swing.JButton submitCountryButton;
    private javax.swing.JButton submitDistrictButton;
    private javax.swing.JButton submitProvinceButton;
    private javax.swing.JPanel tabCantonPanel;
    private javax.swing.JPanel tabCategoryPanel;
    private javax.swing.JPanel tabCountryPanel;
    private javax.swing.JPanel tabDistrictPanel;
    private javax.swing.JPanel tabProvincePanel;
    // End of variables declaration//GEN-END:variables
}
