/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Mau
 */
public class CommentPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommentPanel
     * 
     * 
     */
    String load="asdasdasdsajhkdsajkhdkjhsakjdhksahdjhsajhdjshakjdhjsahdkjsahdkjhsajdhksajhdkjhsajkhdkjhsajkdhksajhdkja";
    String comment;
    String name;
    public CommentPanel() {
        
        initComponents();
        commentText.setText("Esto es un comentario de prueba. La verdad no se queponer equis de"+load+load+load+load+load);
        nameText.setText("Mauricio Muñoz");
        commentText.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        commentText = new javax.swing.JTextArea();
        nameText = new javax.swing.JLabel();

        setBackground(new java.awt.Color(45, 49, 66));
        setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(344, 159));

        commentText.setEditable(false);
        commentText.setBackground(new java.awt.Color(45, 49, 66));
        commentText.setColumns(20);
        commentText.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        commentText.setForeground(new java.awt.Color(255, 255, 255));
        commentText.setRows(5);
        commentText.setTabSize(2);
        commentText.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        commentText.setSelectionColor(new java.awt.Color(239, 131, 84));
        jScrollPane4.setViewportView(commentText);

        nameText.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        nameText.setForeground(new java.awt.Color(255, 255, 255));
        nameText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                    .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentText;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nameText;
    // End of variables declaration//GEN-END:variables
}
