/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

/**
 *
 * @author Mau
 */
public class CommentPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommentPanel
     * 
     * 
     */
    String load="asdasdasdsajhkdsajkhdkjhsakjdhksahdjhsajhdjshakjdhjsahdkjsahdkjhsajdhksajhdkjhsajkhdkjhsajkdhksajhdkja";
    String comment;
    String name;
    public CommentPanel() {
        
        initComponents();
        commentText.setText("Esto es un comentario de prueba. La verdad no se queponer equis de"+load+load+load+load+load);
        nameText.setText("Mauricio Muñoz");
        commentText.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        nameText = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentText = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(45, 49, 66));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(239, 131, 84), 3));
        setMaximumSize(new java.awt.Dimension(344, 159));

        nameText.setBackground(new java.awt.Color(191, 192, 192));
        nameText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nameText.setEnabled(false);
        jScrollPane2.setViewportView(nameText);

        commentText.setBackground(new java.awt.Color(191, 192, 192));
        commentText.setColumns(20);
        commentText.setRows(5);
        commentText.setEnabled(false);
        jScrollPane4.setViewportView(commentText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentText;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane nameText;
    // End of variables declaration//GEN-END:variables
}
