CREATE OR REPLACE PROCEDURE REP_ESTATISTICPROPOSALS_PR
(
    PROPOSAL_CURSOR out sys_refcursor
)
AS
BEGIN
    OPEN PROPOSAL_CURSOR FOR
    SELECT C.NAME, COUNT(P.ID_PROPOSAL) FROM PROPOSAL P
    JOIN PROPOSALXCATEGORY PC ON P.ID_PROPOSAL = PC.ID_PROPOSAL
    JOIN CATEGORY C ON PC.ID_CATEGORY = C.ID_CATEGORY
    GROUP BY C.NAME
    ORDER BY C.NAME;
END;
/
/*ESTADISTICAS DOS le falta :V*/
SELECT C.NAME, COUNT(P.ID_PROPOSAL) FROM PROPOSAL P
    JOIN PERSON PER ON P.ID_PERSON = PER.ID_PERSON
    JOIN COMMUNITY C ON PER.ID_COMMUNITY = C.ID_COMMUNITY
    JOIN DISTRICT D ON C.ID_DISTRICT = D.ID_DISTRICT
    JOIN CANTON CAN ON D.ID_CANTON = CAN.ID_CANTON
    JOIN PROVINCE PRO ON CAN.ID_PROVINCE = PRO.ID_PROVINCE
    JOIN COUNTRY COU ON PRO.ID_COUNTRY = COU.ID_COUNTRY
    GROUP BY C.NAME
    ORDER BY C.NAME;

/*Estadistica tres */
CREATE OR REPLACE PROCEDURE REP_ESTATISTICAGES_PR
(
    MENORES OUT NUMBER,
    VEINTE OUT NUMBER,
    TREINTA OUT NUMBER,
    CUARENTA OUT NUMBER,
    CINCUENTA OUT NUMBER,
    SESENTA OUT NUMBER,
    SETENTA OUT NUMBER,
    DORADOS OUT NUMBER
)
AS
BEGIN
    SELECT COUNT(P.ID_PERSON) INTO MENORES FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=18;
    SELECT COUNT(P.ID_PERSON) INTO VEINTE FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=25;
    SELECT COUNT(P.ID_PERSON) INTO TREINTA FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=35;
    SELECT COUNT(P.ID_PERSON) INTO CUARENTA FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=45;
    SELECT COUNT(P.ID_PERSON) INTO CINCUENTA FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=55;
    SELECT COUNT(P.ID_PERSON) INTO SESENTA FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=65;
    SELECT COUNT(P.ID_PERSON) INTO SETENTA FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12<=75;
    SELECT COUNT(P.ID_PERSON) INTO DORADOS FROM PERSON P
    WHERE MONTHS_BETWEEN(SYSDATE,BIRTHDATE)/12>75;
END;
/*FALTA LA CUATRO */